config/routes.rb
ResumeFixer::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations" }

  root 'home#index'

  resources :home, :only => [:index]
  resources :confirmation, :only => [:index]
  resource :profile, :only => [:edit, :update] do
    resources :timezones, :only => [:new, :update], controller: 'profiles/timezones'
    resources :submissions, :only => [:new, :create], controller: 'profiles/submissions'
    resources :documents, :only => [:index, :create, :destroy, :update], controller: 'profiles/documents' do
      member do
        get 'download'
      end
    end
  end

end

app/controllers/profiles/documents_controller.rb
module Profiles
  class DocumentsController < AuthenticationController
    layout 'profiles'
    respond_to :json, :only => [:create, :destroy, :update]

    def index
      @documents = current_user.documents.submitted.by_updated_at
    end

    def create
      @document = current_user.documents.create(submission_document_params)
      respond_with @document
    end

    def destroy
      @document = current_user.documents.find(params[:id])

      if @document.destroy
        render :json => @document, :status => 200
      else
        render :json => ({:discussion => @document.errors.full_messages}), :status => 422
      end
    end

    def update
      @document = current_user.documents.find(params[:id])
      
      if @document.update(document_params)
        flash[:success] = "Document successfully changed!"
        redirect_to profile_documents_path
      else
        flash[:danger] = "The following errors occurred while processing your request: #{@document.errors.messages[:text_file].join(', ')}."
        redirect_to profile_documents_path
      end
    end 

    def download
      @document = current_user.documents.find(params[:id])
      tempfile = Tempfile.new [SecureRandom.hex, @document.edited_file_url.split('.').last], "#{Rails.root}/tmp"
      File.open(tempfile,'wb') do |file|  
        file.write open(@document.text_file_url).read()
      end
      send_file(tempfile.path)
    end

    private

    def text_file
      params[:text_file] || params[:document][:text_file]
    end

    def document_params
      params.require(:document).permit(:text_file, :description).merge(content_type: text_file.content_type, original_filename: text_file.original_filename)
    end

    def submission_document_params
      params.permit(:text_file, :type).merge(content_type: text_file.content_type, original_filename: text_file.original_filename)
    end
  end
end

app/controllers/profiles/submissions_controller.rb
module Profiles
  class SubmissionsController < AuthenticationController
    layout 'profiles'

    def new
      @submission = current_user.submissions.build
    end

    def create
      SubmissionForm.new(submission_params).save
      flash[:success] = "Thank you for submitting your documents. You should receive a confirmation email of the submission!"
      redirect_to profile_documents_path
    rescue Stripe::CardError => e
      flash[:danger] = e.message
      redirect_to profile_documents_path
    end

    private

    def submission_params
      params.require(:submission).permit(:documents_attributes => [:description]).merge(:card => params[:stripeToken], :user => current_user, :accepted => params[:accepted])
    end
  end
end

app/controllers/profiles/timezones_controller.rb
module Profiles
  class TimezonesController < AuthenticationController
    def new
      @user = current_user
    end

    def update
      @user = current_user

      if @user.update(user_params)
        flash[:success] = "Successfully authenticated from Facebook account."
        redirect_to profile_documents_path
      else
        render :json => @user.errors.full_messages.join(','), :status => 422
      end      
    end

    private

    def user_params
      params.require(:user).permit(:timezone)
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < AuthenticationController
  layout 'profiles'

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      render :json => response_params, :status => 200
    else
      render :json => @user.errors.full_messages.join(','), :status => 422
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :timezone, :password, :password_confirmation)
  end

  def response_params
    field = user_params.keys[0]
    {field: field.split('_').map(&:capitalize).join(' ')}
  end
end

app/views/profiles/edit.html.erb
<h1 class='user_settings text-center'>User Profile</h1>

<!-- Name update -->
<%= form_for @user, url: profile_path, method: :put, :data => {:toggle => 'validator'} do |f| %>
  <div class='form-horizontal'>
    <div class='row'>
    	<div class='form-group'>
        <div class='col-md-1 col-md-offset-3'>
      		<%= f.label :name %>
        </div>
    		<div class='col-md-4'>
    			<%= f.text_field :name, :class => 'form-control', :required => true %>
          <div class="help-block with-errors"></div>
    		</div>
        <div class='col-md-4'>
          <%= f.submit "Update", :class => 'btn btn-primary submit' %>
        </div>
    	</div>
    </div>
  </div>
<% end %>

<!-- Email update -->
<%= form_for @user, url: profile_path, method: :put, :data => {:toggle => 'validator'} do |f| %>
  <div class='form-horizontal'>
    <div class='row'>
    	<div class='form-group'>
        <div class='col-md-1 col-md-offset-3'>
    		  <%= f.label :email %>
        </div>
    		<div class='col-md-4'>
    			<%= f.email_field :email, :class => 'form-control', :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
          <div class="help-block with-errors">Email must follow a standard email format (e.g., 'brian@gmail.com').</div>
    		</div>
        <div class='col-md-4'>
          <%= f.submit "Update", :class => 'btn btn-primary submit' %>
        </div>
    	</div>
    </div>
  </div>
<% end %>

<!-- Phone number update  -->
<%= form_for @user, url: profile_path, method: :put do |f| %>
  <div class='form-horizontal'>
    <div class='row'>
      <div class='form-group'>
        <div class='col-md-1 col-md-offset-3'>
          <label for='user_phone_number'>Phone Number</label>
        </div>
        <div class='col-md-4'>
          <%= f.phone_field :phone_number, :class => 'form-control' %>
          <div class="help-block with-errors"></div>
        </div>
        <div class='col-md-4'>
          <%= f.submit "Update", :class => 'btn btn-primary submit' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<!-- Password update  -->
<%= form_for @user, url: profile_path, method: :put, :data => {:toggle => 'validator'} do |f| %>
  <div class='form-horizontal'>
    <div class='row'>
      <div class='form-group'>
        <div class='col-md-1 col-md-offset-3'>
          <%= f.label :password %>
        </div>
        <div class='col-md-4'>
          <%= f.password_field :password, :id => 'inputPassword', :class => 'form-control', :placeholder => 'Password', :required => true, :data => {:minlength => 8} %>
          <div class="help-block with-errors">Minimum of 8 characters</div>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='form-group'>
        <div class='col-md-4 col-md-offset-4'>
          <%= f.password_field :password_confirmation, :class => 'form-control', :placeholder => 'Password Confirmation', :required => true, :data => {:match => '#inputPassword', :match_error => 'Passwords do not match.'} %>
          <div class="help-block with-errors">Must match the password field.</div>
        </div>
        <div class='col-md-4'>
          <%= f.submit "Update", :class => 'btn btn-primary submit' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<!-- Timezone update  -->
<%= form_for @user, url: profile_path, method: :put, :data => {:toggle => 'validator'} do |f| %>
  <div class='form-horizontal'>
    <div class='row'>
      <div class='form-group'>
        <div class='col-md-1 col-md-offset-3'>
          <%= f.label :timezone %>
        </div>
        <div class='col-md-4'>
          <%= f.collection_select :timezone, ActiveSupport::TimeZone.us_zones, :name, :to_s, {}, :class => 'form-control', :required => true %>
          <div class="help-block with-errors"></div>
        </div>
        <div class='col-md-4'>
          <%= f.submit "Update", :class => 'btn btn-primary submit' %>
        </div>
      </div>
    </div>
  </div>
<% end %>