config/routes.rb
ResumeFixer::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations" }

  root 'home#index'

  resources :home, :only => [:index]
  resources :confirmation, :only => [:index]
  resource :profile, :only => [:edit, :update] do
    resources :timezones, :only => [:new, :update], controller: 'profiles/timezones'
    resources :submissions, :only => [:new, :create], controller: 'profiles/submissions'
    resources :documents, :only => [:index, :create, :destroy, :update], controller: 'profiles/documents' do
      member do
        get 'download'
      end
    end
  end

end

app/views/shared/_config.html.erb
<%= javascript_tag :id => "app_config" do %>
  var frontend_config = <%= raw frontend_config.to_json %>
  window.config = frontend_config
<% end %>

app/views/shared/_flash.html.erb
<% flash.keys.each do |key| %>
  <div class="alert alert-<%= key %> text-center"><%= flash[key] %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-black">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span class="copyright">Copyright &copy; BeamDox 2015</span>
            </div>
            <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                    <li><a href="http://www.twitter.com/beamdox"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="http://www.facebook.com/beamdox"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="https://www.youtube.com/channel/UCnsJ3nvbcf0Q-ZyJRdI1yuQ"><i class="fa fa-youtube"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-inline quicklinks" >
                    <li><a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">Privacy Policy</a></li>
                    <li><a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">Terms of Service</a></li>
                    <li><a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">Refund Policy</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<!-- Portfolio Modal 4 -->
<div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <div class="terms">
                          <%= render "shared/privacy_policy" %>
                        </div>
                        <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Portfolio Modal 5 -->
<div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <div class="terms">
                          <%= render "shared/terms_of_service" %>
                        </div>
                        <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Portfolio Modal 6 -->
<div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                      <div class="terms">
                        <%= render "shared/refund_policy" %>
                      </div>
                      <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_header.html.erb
<nav class='navbar navbar-default navbar-fixed-top'>
  <div class='container'>
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="logo">
        <a class="navbar-brand page-scroll logo-center" href="/home"><%= image_tag 'logos/newlogo5.jpg' %></a>
      </div>    
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right pull-right">
        <li>
          <%= link_to 'New Submission', new_profile_submission_path, :class => 'nav-link' %>
        </li>
        <li>
          <%= link_to 'My Documents', profile_documents_path, :class => 'nav-link' %>
        </li>
        <li role='presentation' class='dropdown'>
          <a class='dropdown-toggle nav-link' data-toggle='dropdown' href='#' role='button' aria-expanded='false'>
            Profile <span class='caret'></span>
          </a>
          <ul class='dropdown-menu dropdown-menu-width' role='menu' aria-labelledby='dropdownMenu1'>
            <li role="presentation" class="text-right"><%= link_to "Settings", edit_profile_path %></li>
            <li role="presentation" class="divider"></li>
            <li role="presentation" class="text-right"><%= link_to 'Log out', destroy_user_session_path, method: :delete, role: "menuitem", tabindex: "-1" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_privacy_policy.html.erb
<h1>PRIVACY POLICY</h1>                           
<h3>SECTION 1 - INFORMATION</h3>
<p>When you register with our website, upload documents, or make a payment for our editing services, we collect the personal information that you provide as a natural part of a buy and sell process. For instance, when you browse our website, we automatically receive your computer’s internet protocol (IP) address. This allows us to learn about your browser and operating system so that we may optimize your user experience. Another example is when you sign up for our website for which we create and collect your authentication data (e.g. email user name and password) so that you may access your personalized user profile and document portal. When you make a payment, we expectedly collect, verify, and process your credit card information like in any purchasing activity. Finally, when you upload documents, such as resumes, cover letters, and essays for us to edit, we store those files in a repository, which makes your user portal useful by tracking file submissions.
</p>
<p>
Email marketing: With your permission, we may send you emails about our website and related services. You may opt out of email updates by going to your profile settings at any time.
</p>
<h3>SECTION 2 - CONSENT</h3> 
<p>
By using our website, registering, submitting documents, employing our services, and making payments, you imply your consent to our collecting relevant information. You may withdraw consent at any time by sending an email to <%= mail_to "customerservice@beamdox.com" %> to close your account. We will completely and permanently delete all of your user history and related information from our website.
</p>
<h3>SECTION 3 - DISCLOSURE</h3>
<p>We may disclose your information if we are required by law or if you violate our Terms of Service.</p>
<h3>SECTION 4 - THIRD-PARTY SERVICES</h3>
<p>
We do not disclose your information to any third-party services, unless the law requires it. We do use a third-party payment service provider called Stripe, which is used to process your credit card payments. Any credit card data is encrypted through the Payment Card Industry Data Security Standard (PCI-DSS). Your purchase transaction data is stored only as long as is necessary to complete your purchase transaction. After that is complete, your purchase transaction information is deleted. Stripe uses its own privacy policies in respect to the information we are required to provide to them for your purchase-related transactions. We are not responsible for the privacy practices of other sites or third –party services, but we recommend that you read about them <%= link_to "here", 'https://stripe.com/gb/privacy' %>.
</p>
<h3>SECTION 5 - SECURITY</h3>
<p>To protect your personal information, we take reasonable precautions and industry best practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed. If you provide us with your credit card information, the information is encrypted using secure socket layer technology (SSL) and stored with an AES-256 encryption. Although no method of transmission over the Internet or electronic storage is 100% secure, we follow all PCI-DSS requirements and implement additional generally accepted industry standards. 
</p>
<h3>SECTION 6 - COOKIES</h3>
<p>Cookies are small files that are stored on a user's computer. They are designed to hold a modest amount of data specific to a particular client and website, and can be accessed either by the web server or the client computer. This allows the server to deliver a page tailored to a particular user, or the page itself can contain some script which is aware of the data in the cookie and so is able to carry information from one visit to the website (or related site) to the next. Our website stores minimum cookies. You may delete them and other cookies by going to your internet browser settings. 
</p>
<h3>SECTION 7 - AGE OF CONSENT</h3>
<p>By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site. 
</p>
<h3>SECTION 8 - CHANGES TO THIS PRIVACY POLICY</h3>
<p>We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the website. If we make material changes to this policy, we will notify you here that it has been updated, so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we use and/or disclose it. If our store is acquired or merged with another company, your information may be transferred to the new owners so that we may continue to sell products to you. 
</p>
<h3>QUESTIONS AND CONTACT INFORMATION</h3>
<p>If you would like to: access, correct, amend or delete any personal information we have about you, register a complaint, or simply want more information, please contact our Privacy Compliance Officer at <%= mail_to "customerservice@beamdox.com" %>.
</p>

app/views/shared/_refund_policy.html.erb
<h1>Refund Policy</h1>
<p>
  Our policy is 7 days. If 7 days have gone by since your purchase transaction, we cannot offer you a refund, partial refund, or exchange related to that purchase transaction. By using our website and services, you agree to our Terms of Service. 
</p>
<p>
  Refunds are assessed on the basis of each document submitted. If you made an erroneous submission, you may return to your user portal to make changes so long as the “Status” of the document is neither “In Revision” nor “Completed.” When a document status is “In Revision” or “Completed,” it means our editors have either already begun significant work on it or have completed its revision. Both cases indicate significant consumption of our service, time, and labor. We cannot issue partial refunds on any individual document submission.
</p>
<p>
  You are eligible for a full refund on a document submission if BeamDox has not completed the document revision within 24 hours of the file submission. All document submissions are listed and time-stamped in your user portal under My Documents. It is your responsibility to check the document status. As a courtesy, we will send you a notification when your document has been revised completely. Your failure to notice that the document revision was complete within 24 hours is not proof or indication that we did not complete the service within 24 hours.
</p>
<p>
  You may not dispute the “quality” of our service to request a refund. By using our services, you agree that our services meet your expectations. All of our editors work extremely hard to make significant improvements to your documents. 
</p>
<p>
  To request a refund, you must email <%= mail_to "customerservice@beamdox.com" %>. Please indicate which file you are seeking refund for. Approved refunds will be processed within 5 to 7 business days, and the credit will automatically be applied to the credit card you used for the original payment. If you haven’t received a refund yet, first check your credit card statement or bank account again. Even though we have issued the refund, it may take some time before your refund is officially posted. If you’ve done all of this and you still have not received your refund yet, please contact us at <%= mail_to "customerservice@beamdox.com" %>.
</p>

app/views/shared/_static_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        <div class="logo">
              <a class="navbar-brand page-scroll logo-center" href="/home"><%= image_tag 'logos/newlogo5.jpg' %></a>
        </div>    
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right pull-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll nav-link" href="#services">Services</a>
                </li>
                <li>
                    <a class="page-scroll nav-link" href="#process">Process</a>
                </li>
                <li>
                    <a class="page-scroll nav-link" href="#prices">Prices</a>
                </li>
                <li>
                    <a class="page-scroll nav-link" href="#team">Team</a>
                </li>
                  
                <% if signed_in? %>
                  <li>
                    <%= link_to "Documents", profile_documents_path, :class => 'nav-link' %>
                  </li>
                  <li role='presentation' class='dropdown'>
                    <a class='dropdown-toggle nav-link' data-toggle='dropdown' href='#' role='button' aria-expanded='false'>
                    Profile <span class='caret'></span>
                    </a>
                  <ul class='dropdown-menu dropdown-menu-width' role='menu' aria-labelledby='dropdownMenu1'>
                    <li role="presentation" class="text-right"><%= link_to "Settings", edit_profile_path %></li>
                    <li role="presentation" class="divider"></li>
                    <li role="presentation" class="text-right"><%= link_to 'Log out', destroy_user_session_path, method: :delete, role: "menuitem", tabindex: "-1" %>
                  </li>
                <% else %>
                  <li>
                      <%= link_to "Sign Up", '#', :data => {:toggle => 'modal', :target => '.signup-modal'}, :class => 'highlighted-link nav-link'%>
                  </li>                
                  <li>
                      <%= link_to "Log In", '#', :data => {:toggle => 'modal', :target => '.login-modal'}, :class => 'highlighted-link nav-link' %>
                  </li>                
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<!-- Signup modal -->
<div class='modal fade signup-modal'>
  <div class='modal-dialog modal-sm'>
    <div class='modal-content modal-signup-body'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class='modal-title text-center'>Sign up with Beamdox</h4>
      </div>

      <div class='modal-body'>
        <button class='btn btn-primary center-block email-signup'>Sign up with Email</button>
        <br><div class='text-center'>OR</div><br>
        <%= link_to image_tag("fbsignup.jpg", class: 'img-responsive center-block'), user_omniauth_authorize_path(:facebook), class: 'facebook-login' %>
      </div>
    </div>
  </div>
</div>

<!-- Signup through email modal -->
<div class='modal fade email-signup-modal'>
  <div class='modal-dialog modal-sm'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class='modal-title text-center'>Sign up with Beamdox</h4>
      </div>

      <%= form_for :user, url: user_registration_path, :data => {:toggle => 'validator'} do |f| %>
        <div class='form-group'><br>
          <%= f.label :name, :class => 'control-label' %>
          <%= f.text_field :name, :class => 'form-control', :placeholder => "Full Name", :required => true %>
          <div class="help-block with-errors"></div>
        </div>

        <div class='form-group'>
          <%= f.label :email, :class => 'control-label' %>
          <%= f.email_field :email, :class => 'form-control', :placeholder => "Email Address", :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
          <div class="help-block with-errors">Email must follow a standard email format (e.g., 'brian@gmail.com').</div>
        </div>
        <div class='form-group'>
          <%= f.label :password, :class => 'control-label' %>
          <%= f.password_field :password, :id => 'inputPassword', :class => 'form-control', :placeholder => "Password", :required => true, :data => {:minlength => 8} %>
          <div class="help-block with-errors">Minimum of 8 characters</div>
        </div>

        <div class='form-group'>
          <%= f.password_field :password_confirmation, :class => 'form-control', :placeholder => "Confirm Password", :required => true, :data => {:match => '#inputPassword', :match_error => 'Passwords do not match.'} %>
          <div class="help-block with-errors">Must match the password field.</div>
        </div>

        <div class='form-group'>
          <%= f.label :timezone, :class => 'control-label' %>
          <%= f.collection_select :timezone, ActiveSupport::TimeZone.us_zones, :name, :to_s, {}, :class => 'form-control', :required => true %>
        </div>
        <%= f.submit "Sign Up", :class => 'btn btn-primary center-block' %>
      <% end %>
    </div>
  </div>
</div>


<!-- Login modal -->
<div class='modal fade login-modal'>
  <div class='modal-dialog modal-sm'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class='modal-title text-center'>Log In</h4>
      </div>
      <%= form_for :user, url: user_session_path, :data => {:toggle => 'validator'} do |f| %>
        <div class='form-group'>
          <br><%= f.label :email %>
          <%= f.email_field :email, :class => 'form-control', :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
          <div class="help-block with-errors"></div>
        </div>

        <div class='form-group'>
          <%= f.label :password %>
          <%= f.password_field :password, :class => 'form-control', :required => true %>
          <div class="help-block with-errors"></div>
        </div>

        <div class="form-group">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>

        <%= f.submit "Log in", class: 'btn btn-primary center-block' %>
      <% end %><br>
      <div class='text-center'>
        Don't have an account?<%= link_to 'Sign up!', '#', :class => 'email-signup' %><br>
        Forgot password? <%= link_to 'Find Password', '#', :class => 'forgot-password' %>
      </div><br>
      <div class='text-center'>OR</div><br>
      <%= link_to image_tag("fblogin.jpg", class: 'facebook-login img-responsive center-block'), user_omniauth_authorize_path(:facebook) %>
    </div>
  </div>
</div>

<!-- Forgotten password modal -->
<div class='modal fade forgotten-password-modal'>
  <div class='modal-dialog modal-sm'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class='modal-title text-center'>Recover Password</h4>
      </div>
      <%= form_for :user, url: user_password_path, :data => {:toggle => 'validator'} do |f| %>
        <div class='form-group'>
          <%= f.label :email %>
          <%= f.email_field :email, :class => 'form-control', :required => true %>
          <div class="help-block with-errors"></div>
        </div>

        <%= f.submit "Send reset password instructions", class: 'btn btn-primary center-block' %>
      <% end %><br>
      <div class='text-center'>OR</div><br>
      <%= link_to image_tag("fblogin.jpg", class: 'facebook-login img-responsive center-block'), user_omniauth_authorize_path(:facebook) %>
    </div>
  </div>
</div>