config/routes.rb
ResumeFixer::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations" }

  root 'home#index'

  resources :home, :only => [:index]
  resources :confirmation, :only => [:index]
  resource :profile, :only => [:edit, :update] do
    resources :timezones, :only => [:new, :update], controller: 'profiles/timezones'
    resources :submissions, :only => [:new, :create], controller: 'profiles/submissions'
    resources :documents, :only => [:index, :create, :destroy, :update], controller: 'profiles/documents' do
      member do
        get 'download'
      end
    end
  end

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  has_many :documents
  accepts_nested_attributes_for :documents

  before_create :set_total_amount

  private

  def set_total_amount
    self.amount = documents.map(&:price).sum
  end
end

app/controllers/profiles/documents_controller.rb
module Profiles
  class DocumentsController < AuthenticationController
    layout 'profiles'
    respond_to :json, :only => [:create, :destroy, :update]

    def index
      @documents = current_user.documents.submitted.by_updated_at
    end

    def create
      @document = current_user.documents.create(submission_document_params)
      respond_with @document
    end

    def destroy
      @document = current_user.documents.find(params[:id])

      if @document.destroy
        render :json => @document, :status => 200
      else
        render :json => ({:discussion => @document.errors.full_messages}), :status => 422
      end
    end

    def update
      @document = current_user.documents.find(params[:id])
      
      if @document.update(document_params)
        flash[:success] = "Document successfully changed!"
        redirect_to profile_documents_path
      else
        flash[:danger] = "The following errors occurred while processing your request: #{@document.errors.messages[:text_file].join(', ')}."
        redirect_to profile_documents_path
      end
    end 

    def download
      @document = current_user.documents.find(params[:id])
      tempfile = Tempfile.new [SecureRandom.hex, @document.edited_file_url.split('.').last], "#{Rails.root}/tmp"
      File.open(tempfile,'wb') do |file|  
        file.write open(@document.text_file_url).read()
      end
      send_file(tempfile.path)
    end

    private

    def text_file
      params[:text_file] || params[:document][:text_file]
    end

    def document_params
      params.require(:document).permit(:text_file, :description).merge(content_type: text_file.content_type, original_filename: text_file.original_filename)
    end

    def submission_document_params
      params.permit(:text_file, :type).merge(content_type: text_file.content_type, original_filename: text_file.original_filename)
    end
  end
end

app/controllers/profiles/submissions_controller.rb
module Profiles
  class SubmissionsController < AuthenticationController
    layout 'profiles'

    def new
      @submission = current_user.submissions.build
    end

    def create
      SubmissionForm.new(submission_params).save
      flash[:success] = "Thank you for submitting your documents. You should receive a confirmation email of the submission!"
      redirect_to profile_documents_path
    rescue Stripe::CardError => e
      flash[:danger] = e.message
      redirect_to profile_documents_path
    end

    private

    def submission_params
      params.require(:submission).permit(:documents_attributes => [:description]).merge(:card => params[:stripeToken], :user => current_user, :accepted => params[:accepted])
    end
  end
end

app/controllers/profiles/timezones_controller.rb
module Profiles
  class TimezonesController < AuthenticationController
    def new
      @user = current_user
    end

    def update
      @user = current_user

      if @user.update(user_params)
        flash[:success] = "Successfully authenticated from Facebook account."
        redirect_to profile_documents_path
      else
        render :json => @user.errors.full_messages.join(','), :status => 422
      end      
    end

    private

    def user_params
      params.require(:user).permit(:timezone)
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < AuthenticationController
  layout 'profiles'

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      render :json => response_params, :status => 200
    else
      render :json => @user.errors.full_messages.join(','), :status => 422
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :timezone, :password, :password_confirmation)
  end

  def response_params
    field = user_params.keys[0]
    {field: field.split('_').map(&:capitalize).join(' ')}
  end
end

app/views/profiles/submissions/new.html.erb
<section class="col-md-12">
  <h1 class='text-center page_title'>Submit Documents</h1>
  <%= render 'shared/flash' %>
  <h5 class='text-center'>Drag and drop your files below. Acceptable file types include .pdf, .txt, .doc, .docx., .rtf</h5>

  <div class='row'>
    <div class='col-md-4' id='resume_section'>
      <h3 class='text-center'>$100/Resume</h3>
      <%= file_field_tag 'text_file', multiple: true, type: :file, class: 'document', id: 'resume', :data => {:type => 'Resume'} %>
    </div>
    <div class='col-md-4' id='cover_letter_section'>
      <h3 class='text-center'>$100/Cover Letter</h3>
      <%= file_field_tag 'text_file', multiple: true, type: :file, class: 'document', id: 'cover_letter', :data => {:type => 'Cover Letter'} %>
    </div>
    <div class='col-md-4' id='essay_section'>
      <h3 class='text-center'>$250/Essay</h3>
      <%= file_field_tag 'text_file', multiple: true, type: :file, class: 'document', id: 'essay', :data => {:type => 'Essay'} %>
    </div>
  </div>

  <%= form_for @submission, url: profile_submissions_path, multipart: true, :html => {:id => 'payment_form'} do |f| %>
    <div class='selected_documents_container well'>
      <div class='selected_documents'>
        <h4 class='text-center'>Selected Documents</h4>
        <div class='table-responsive'>
          <table class='table'>
            <thead>
              <th><strong>File Type</strong></th>
              <th><strong>File Name</strong></th>
              <th><strong>Upload Time</strong></th>
              <th><strong>Price</strong></th>
              <th><strong>Add Comments</strong></th>
              <th><strong></strong></th>
            </thead>
            <tbody class='documents_list'>
            </tbody>
          </table>
        </div>
      </div>
      <div class="total-price text-center">
        <h3>TOTAL PRICE: $<span id="total_price">0</span></h3>
      </div>

    </div>
    <div class='row text-center'>
      <%= check_box_tag :accepted, '', false, :class => 'accept-checkbox' %>
      <label for='accepted'>
        By checking here, I confirm that I have completely read and agree to the 
        <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">Privacy Policy</a>, 
        <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">Terms of Service</a>, and 
        <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">Refund Policy</a> of www.BeamDox.com.
      </label>
    </div>
    <div class='text-center' style="margin-top:10px">
      <%= button_tag 'Submit & Pay', :class => 'btn btn-primary', :id => 'submit_button' %>
    </div>
  <% end %>  
</section>

<!-- Pay modal -->
<div class="modal fade payment-modal">
  <div class='modal-dialog modal-sm'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class='modal-title text-center'>Submit Documents</h4>
        <h5 class='modal-subtitle text-center'><%= current_user.email %></h5> 
      </div>
      <div class='modal-body text-center'>
        <p>Use your credit card ending in <%= current_user.last_4_digits %>.</p>

        <button id='pay_with_old_card' class='btn btn-primary pay-btn-margin'>Pay</button>
        <p>OR</p>
        <p>
          Pay with a <%= link_to "different card", '#', :id => 'open-new-card-modal' %>.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- New credit card modal -->
<div class='modal fade new-card-modal'>
  <div class='modal-dialog modal-sm'>
    <div class='modal-content'>
      <form action="" method="POST" id='payment-form'>
        <div class='modal-header'>
          <button type='button' class='close' data-dismiss='modal' aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class='modal-title text-center'>Submit Documents</h4>
          <h5 class='modal-subtitle text-center'><%= current_user.email %></h5> 
        </div>        
        <div class='modal-body'>
          <div class='text-center'>
            <span class="payment-errors"></span>
          </div>
          <h5 class='text-center'><strong>Accepted Payment Options</strong></h5>
          <div class='credit_cards text-center'>
            <div class='row'>
              <%= image_tag 'credit_cards/american_express.jpg' %>
              <%= image_tag 'credit_cards/mastercard.jpg' %>
              <%= image_tag 'credit_cards/visa.jpg' %>
            </div>
            <div class='row'>
              <%= image_tag 'credit_cards/discover.jpg' %>
              <%= image_tag 'credit_cards/jcb.jpg' %>
              <%= image_tag 'credit_cards/dinersclub.jpg' %>
            </div>
          </div>
          <div class="form-group payment-card-margin">
            <label for='card_number'>
              <span>Card Number</span>
            </label>
            <input type="text" id='card_number' class='card_number form-control' size="20"/>
          </div>

          <div class="form-group payment-card-margin">
            <label for='card_cvc'>
              <span>CVC</span>
            </label>
            <input type="text" id='card_cvc' class='card_cvc form-control' size="4"/>
          </div>

          <div class="form-group payment-card-margin">
            <label for='card_expr'>
              <span>Expiration (MM/YYYY)</span>
            </label>
            <input type="text" id='card_expr' class='card_expr form-control' size="6"/>
          </div>
        </div>
        <div class='modal-footer'>
          <% if current_user.is_customer? %>
            <%= button_tag 'Back', :class => 'btn btn-default', :id => 'open-payment-modal' %>
          <% end %>

          <button type='submit' class='btn btn-primary'>Pay</button>
        </div>
      </form>
    </div>
  </div>
</div>

<%= stripe_javascript_tag %>
<% provide(:title, "New Submission") %>