config/routes.rb
ResumeFixer::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations" }

  root 'home#index'

  resources :home, :only => [:index]
  resources :confirmation, :only => [:index]
  resource :profile, :only => [:edit, :update] do
    resources :timezones, :only => [:new, :update], controller: 'profiles/timezones'
    resources :submissions, :only => [:new, :create], controller: 'profiles/submissions'
    resources :documents, :only => [:index, :create, :destroy, :update], controller: 'profiles/documents' do
      member do
        get 'download'
      end
    end
  end

end

app/models/document.rb
class Document < ActiveRecord::Base
  include ActionView::Helpers::TextHelper

  mount_uploader :text_file, TextFileUploader
  mount_uploader :edited_file, EditedFileUploader
  belongs_to :user
  belongs_to :submission

  scope :submitted, -> { where(submitted: true) }
  scope :by_updated_at, -> { order(:updated_at => :desc) }
  scope :over_ten_minutes, -> { where(arel_table[:created_at].lt(10.minutes.ago)) }
  scope :matching, -> { where(status: 'matching') }

  validates_presence_of :text_file
  validates_presence_of :type

  before_save :format_description
  before_save :set_to_complete
  # after_create :set_to_editing

  def formatted_type
    self.class.name.underscore.split('/').last
  end

  def formatted_created_at
    self.updated_at.strftime('%m/%d/%C @%l:%M %p')
  end

  def formatted_filename
    if original_filename.length > 20
      self.original_filename.sub(/(.{20})(.*)/, '\1') + '...'
    else
      original_filename
    end
  end

  private

  def format_description
    if description.present?
      self.description = simple_format(description)
    end
  end

  def set_to_editing
    Documents::ChangeStatusWorker.perform_at(1.minute.from_now, id, 'editing')
  end

  def set_to_complete
    if edited_file.present?
      self.status = 'complete'
    end
  end
end

app/models/documents/cover_letter.rb
class Documents::CoverLetter < Document
  def price
    100
  end
end

app/models/documents/essay.rb
class Documents::Essay < Document
  def price
    250
  end
end

app/models/documents/resume.rb
class Documents::Resume < Document
  def price
    100
  end
end

app/controllers/profiles/documents_controller.rb
module Profiles
  class DocumentsController < AuthenticationController
    layout 'profiles'
    respond_to :json, :only => [:create, :destroy, :update]

    def index
      @documents = current_user.documents.submitted.by_updated_at
    end

    def create
      @document = current_user.documents.create(submission_document_params)
      respond_with @document
    end

    def destroy
      @document = current_user.documents.find(params[:id])

      if @document.destroy
        render :json => @document, :status => 200
      else
        render :json => ({:discussion => @document.errors.full_messages}), :status => 422
      end
    end

    def update
      @document = current_user.documents.find(params[:id])
      
      if @document.update(document_params)
        flash[:success] = "Document successfully changed!"
        redirect_to profile_documents_path
      else
        flash[:danger] = "The following errors occurred while processing your request: #{@document.errors.messages[:text_file].join(', ')}."
        redirect_to profile_documents_path
      end
    end 

    def download
      @document = current_user.documents.find(params[:id])
      tempfile = Tempfile.new [SecureRandom.hex, @document.edited_file_url.split('.').last], "#{Rails.root}/tmp"
      File.open(tempfile,'wb') do |file|  
        file.write open(@document.text_file_url).read()
      end
      send_file(tempfile.path)
    end

    private

    def text_file
      params[:text_file] || params[:document][:text_file]
    end

    def document_params
      params.require(:document).permit(:text_file, :description).merge(content_type: text_file.content_type, original_filename: text_file.original_filename)
    end

    def submission_document_params
      params.permit(:text_file, :type).merge(content_type: text_file.content_type, original_filename: text_file.original_filename)
    end
  end
end

app/controllers/profiles/submissions_controller.rb
module Profiles
  class SubmissionsController < AuthenticationController
    layout 'profiles'

    def new
      @submission = current_user.submissions.build
    end

    def create
      SubmissionForm.new(submission_params).save
      flash[:success] = "Thank you for submitting your documents. You should receive a confirmation email of the submission!"
      redirect_to profile_documents_path
    rescue Stripe::CardError => e
      flash[:danger] = e.message
      redirect_to profile_documents_path
    end

    private

    def submission_params
      params.require(:submission).permit(:documents_attributes => [:description]).merge(:card => params[:stripeToken], :user => current_user, :accepted => params[:accepted])
    end
  end
end

app/controllers/profiles/timezones_controller.rb
module Profiles
  class TimezonesController < AuthenticationController
    def new
      @user = current_user
    end

    def update
      @user = current_user

      if @user.update(user_params)
        flash[:success] = "Successfully authenticated from Facebook account."
        redirect_to profile_documents_path
      else
        render :json => @user.errors.full_messages.join(','), :status => 422
      end      
    end

    private

    def user_params
      params.require(:user).permit(:timezone)
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < AuthenticationController
  layout 'profiles'

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      render :json => response_params, :status => 200
    else
      render :json => @user.errors.full_messages.join(','), :status => 422
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :timezone, :password, :password_confirmation)
  end

  def response_params
    field = user_params.keys[0]
    {field: field.split('_').map(&:capitalize).join(' ')}
  end
end

app/views/profiles/documents/index.html.erb
<section class='documents_index'>
  <div class='text-center'>
    <h1>My Documents</h1><br>
  </div>
  <%= render 'shared/flash' %>
  <% if @documents.empty? %>
    <div class='text-center'>
      <p>You currently don't have any documents uploaded. <%= link_to "Click here", new_profile_submission_path %> to create a submission.</p>
    </div>
  <% else %>
    <div class='table-responsive'>
      <table class='table text-center'>
        <tr>
          <th>Time Submitted</th>
          <th>File Name</th>
          <th>Review Status</th>
          <th>More Info</th>
        </tr>
        <% @documents.each do |document| %>
          <tr>
            <td><%= document.formatted_created_at %></td>
            <td>
              <% if document.status == 'matching' %>
                <a href='#' data-toggle='modal' data-target='#upload-modal' data-document-id="<%= document.id %>"><i class="fa fa-refresh" aria-hidden="true"></i></a>
              <% end %>
              <%= link_to document.formatted_filename, '#', :data => {:toggle => 'modal', :target => '#preview-modal', :url => "https://docs.google.com/gview?url=#{document.text_file_url}&embedded=true", :title => document.original_filename} %>
              </td>
            <td>
              <%= document.status.capitalize %>
              <% if document.status == 'complete' %>
                <a href=<%= download_profile_document_path(document.id) %>><span class="glyphicon glyphicon-download" aria-hidden="true"></span></a>
              <% end %>
            </td>
            <td>
              <a href='#' data-toggle='modal' data-target='#info-modal' data-user-comments="<%= document.description %>" data-editor-comments="<%= document.feedback %>" data-file-name="<%= document.original_filename %>" data-file-type="<%= document.formatted_type.capitalize %>" data-price="<%= document.price %>">
                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
              </a>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>
</section>

<div class="portfolio-modal modal fade" id="preview-modal">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
        <div class="modal-body">
          <h1 id='document-title'></h1>
          <div class="row">
            <iframe src='' id='embedded-preview' width='1000px' height='800px'></iframe>
          </div>
          <div class='row'>
            <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id='upload-modal'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Change File</h4>
      </div>
      <div class="modal-body">
        <p><strong>NOTE:</strong> You may replace this document as long as the status is NOT “In Editing” or “Complete.” </p>
        <p><strong>NOTE:</strong> You may only substitute documents of the same type: cover letter for another cover letter, resume for another resume, or essay for another essay. If you replace with a mismatching document type, we will not edit it. We will issue an automatic refund for that document.</p>
        <%= form_for :document, url: profile_document_path(1), method: :put, :html => {:class => 'change-file-form'} do |f| %>
          <div class='form-group'>
            <%= f.file_field :text_file %>
          </div>

          <div id='change-file-description'></div>

          <%= f.submit "Confirm", class: 'btn btn-primary confirm', :disabled => true %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id='info-modal'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">More Information</h4>
      </div>
      <div class="modal-body">
        <div id='file-name'></div>
        <div id='file-type'></div>
        <div id='price'></div>
        <div id='user-comments'></div>
        <div id='editor-commments'></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<% provide(:title, "My Documents") %>